#ifndef FLOWER_STALLDETECTIONTUNING_H
#define FLOWER_STALLDETECTIONTUNING_H

#define NUM_STALL_VALUES 22
#define SPEED_COLUMN 0
#define SGT_COLUMN 1
#define STALL_DETECTION_COLUMN 2

extern const int STALL_TABLE[NUM_STALL_VALUES][3];

#endif //FLOWER_STALLDETECTIONTUNING_H
